movie/urls.py
# urls.py

from django.urls import path

from . import views
from .views import register, login_view, home_view, note, add

urlpatterns = [

    path('', views.login_view, name='login'),
    path('search/', views.search, name='search'),
    path('register/', views.register, name='register'),
    path('home/', views.home_view, name='home'),
    path('add/', views.add, name='add'),

    path('note/', views.note, name='note'),
    # path('favorite/', views.favorite, name='favorite'),
    # path('favorite/', views.favorite_list, name='favorite'),
    path('api/movie-details/', views.get_movie_details, name='movie-details'),
    path('search/', views.search, name='search'),
    path('profile/', views.profile, name='profile'),
    path('home/', views.review, name='home'),
    path('review/<int:id>/', views.review_page, name='review_page'),
    path('home/favorite/', views.favorite, name='favorite'),
    path('favorites/', views.favorite_list, name='favorite_list'),
    path('delete/<int:movie_id>/',views.delete,name='delete'),
    path('edit/<int:movie_id>/', views.edit, name='edit'),

]

movielast/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movie/models.py
from datetime import timezone

from django.contrib.auth.base_user import BaseUserManager
from django.db import models
from django.utils import timezone

from django.contrib.auth.models import User

from movielast import settings


class CustomUser(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    gender = models.CharField(max_length=10, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')])

    def __str__(self):
        return self.username


# models.py


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=500)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(max_length=241)
    release_date = models.DateField()
    actors = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    trailer_link = models.URLField()
    image = models.ImageField(upload_to='movie_images/')
    favorited_by = models.ManyToManyField(User, related_name='favorite_movies', blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='movies')  # New field


def __str__(self):
    return self.title


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profile_images', default='default.jpg')
    mobile = models.CharField(max_length=15, blank=True, null=True)
    address1 = models.CharField(max_length=255, blank=True, null=True)
    address2 = models.CharField(max_length=255, blank=True, null=True)
    postcode = models.CharField(max_length=10, blank=True, null=True)
    state = models.CharField(max_length=50, blank=True, null=True)
    area = models.CharField(max_length=50, blank=True, null=True)
    education = models.CharField(max_length=100, blank=True, null=True)
    country = models.CharField(max_length=50, blank=True, null=True)
    region = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return f'{self.user.username} Profile'


class review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Movie, on_delete=models.CASCADE)
    review_desp = models.CharField(max_length=100)
    rating = models.IntegerField()

    def __str__(self):
        return f'{self.user.username} - {self.item.title}'


class FavoriteMovie(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    added_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'movie')

    def __str__(self):
        return f"{self.user.username} - {self.movie.title}"

templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete Movie</title>
</head>
<body>

{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center align-items-center" style="height: 100vh;">
        <div class="col-md-6 col-lg-4">
            <form method="POST">
                {% csrf_token %}
                <div class="card bg-dark text-white">
                    <img src="{{ movie.image.url }}" class="card-img-top" alt="{{ movie.title }}" style="max-height: 240px; object-fit: cover;">
                    <div class="card-body text-center">
                        <h5 class="card-title" style="text-color:white">{{ movie.title }}</h5>
                        <p class="card-text"><b>Are you sure you want to delete this movie?</b></p>
                        <button type="submit" class="btn btn-danger">Confirm</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}




</body>
</html>

templates/edit.html
{% load static %}
<!DOCTYPE html>
<html >
<head>
  <!-- Site made with Mobirise Online Website Builder v5.9.13, https://a.mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v5.9.13, a.mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="assets/images/photo-1542204165-65bf26472b9b.jpeg" type="image/x-icon">
  <meta name="description" content="Explore the latest movies with free download options. Get access to movie photos, descriptions, links, and ratings.">
  <title>Free Movie Downloads</title>
  <link rel="stylesheet" href="https://r.mobirisesite.com/430795/assets/web/assets/mobirise-icons2/mobirise2.css?rnd=1715149129646">
  <link rel="stylesheet" href="https://r.mobirisesite.com/430795/assets/bootstrap/css/bootstrap.min.css?rnd=1715149129646">
  <link rel="stylesheet" href="https://r.mobirisesite.com/430795/assets/bootstrap/css/bootstrap-grid.min.css?rnd=1715149129646">
  <link rel="stylesheet" href="https://r.mobirisesite.com/430795/assets/bootstrap/css/bootstrap-reboot.min.css?rnd=1715149129646">
  <link rel="stylesheet" href="https://r.mobirisesite.com/430795/assets/dropdown/css/style.css?rnd=1715149129646">
  <link rel="stylesheet" href="https://r.mobirisesite.com/430795/assets/socicon/css/styles.css?rnd=1715149129646">
  <link rel="stylesheet" href="https://r.mobirisesite.com/430795/assets/theme/css/style.css?rnd=1715149129646">
  <link rel="preload" href="https://fonts.googleapis.com/css2?family=Brygada+1918:wght@400;700&display=swap&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'">
  <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Brygada+1918:wght@400;700&display=swap&display=swap"></noscript>
  <link rel="stylesheet" href="https://r.mobirisesite.com/430795/assets/css/mbr-additional.css?rnd=1715149129646" type="text/css">
 <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">



</head>

<body>
<h3 class="mbr-section-title mbr-fonts-style mb-4 display-2 text-center">
						<strong>EDIT THE MOVIE "{{ movie.title }}"</strong>
					</h3>
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-12 col-md-12 col-lg-6 image-wrapper">
				<img class="w-100" src="{% static 'img/movieadd.png' %}"alt="Mobirise Website Builder">
                 <div>

                <p><h4><b>Are you a movie enthusiast looking to organize and curate your favorite films? Look no further! Our platform offers you a seamless experience to add and manage your liked movies along with their details.<br>
                     <br>

Adding movies to your collection is a breeze. Simply input the title, description, release date, actors, category, trailer link, and even upload an image to represent the movie. With our user-friendly interface, you can quickly fill in the details and hit submit.<br>
<br>
Once added, your movies will be neatly displayed in your personal collection. You can easily edit any movie's details whenever you want, ensuring that your collection stays up-to-date and accurately reflects your tastes.</b></h4></p>
            </div>
			</div>

<div class="col-12 col-md-12 col-lg">
    <div class="text-wrapper align-left">
        <form method="post" action="{% url 'edit' movie.id %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="title">Title:</label>
                <input type="text" class="form-control" id="title" name="title" value="{{ movie.title }}">
            </div>
            <div class="form-group">
                <label for="description">Description:</label>
                <textarea class="form-control" id="description" name="description" rows="3">{{ movie.description }}</textarea>
            </div>
            <div class="form-group">
                <label for="release_date">Release Date:</label>
                <input type="date" class="form-control" id="release_date" name="release_date" value="{{ movie.release_date }}">
            </div>
            <div class="form-group">
                <label for="actors">Actors:</label>
                <input type="text" class="form-control" id="actors" name="actors" value="{{ movie.actors }}">
            </div>
            <div class="form-group">
                <label for="category">Category:</label>
                <select class="form-control" id="category" name="category">
                    <option value="malayalam_movie" {% if movie.category == 'malayalam_movie' %}selected{% endif %}>Malayalam Movie</option>
                    <option value="english_movie" {% if movie.category == 'english_movie' %}selected{% endif %}>English Movie</option>
                    <option value="tamil_movie" {% if movie.category == 'tamil_movie' %}selected{% endif %}>Tamil Movie</option>
                </select>
            </div>
            <div class="form-group">
                <label for="trailer_link">Trailer Link:</label>
                <input type="url" class="form-control" id="trailer_link" name="trailer_link" value="{{ movie.trailer_link }}">
            </div>
            <div class="form-group">
                <label for="image">Image:</label>
                <input type="file" class="form-control-file" id="image" name="image">
                <br>
                {% if movie.image %}
                    <img src="{{ movie.image.url }}" alt="{{ movie.title }}" style="max-height: 240px; object-fit: cover;">
                {% endif %}
            </div>
            <input type="submit" class="btn btn-success" value="Save Changes">
        </form>
    </div>
</div>

  </body>
</html>

templates/error_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>
</head>
<body>
    <h1>Error</h1>
    <p>{{ error_message }}</p>
    <a href="{% url 'home' %}">Return to Home</a> <!-- Assuming you have a URL pattern named 'home_page' -->
</body>
</html>

templates/favorite.html
{% load static %}
{% load custom_filters %}
<!DOCTYPE html>
<html>
<head>
  <!-- Site made with Mobirise Online Website Builder v5.9.13, https://a.mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v5.9.13, a.mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="{% static 'assets/images/photo-1542204165-65bf26472b9b.jpeg' %}" type="image/x-icon">
  <meta name="description" content="Explore the latest movies with free download options. Get access to movie photos, descriptions, links, and ratings.">
  <title>Free Movie Downloads</title>
  <link rel="stylesheet" href="https://r.mobirisesite.com/430795/assets/web/assets/mobirise-icons2/mobirise2.css?rnd=1715149129646">
  <link rel="stylesheet" href="https://r.mobirisesite.com/430795/assets/bootstrap/css/bootstrap.min.css?rnd=1715149129646">
  <link rel="stylesheet" href="https://r.mobirisesite.com/430795/assets/bootstrap/css/bootstrap-grid.min.css?rnd=1715149129646">
  <link rel="stylesheet" href="https://r.mobirisesite.com/430795/assets/bootstrap/css/bootstrap-reboot.min.css?rnd=1715149129646">
  <link rel="stylesheet" href="https://r.mobirisesite.com/430795/assets/dropdown/css/style.css?rnd=1715149129646">
  <link rel="stylesheet" href="https://r.mobirisesite.com/430795/assets/socicon/css/styles.css?rnd=1715149129646">
  <link rel="stylesheet" href="https://r.mobirisesite.com/430795/assets/theme/css/style.css?rnd=1715149129646">
  <link rel="preload" href="https://fonts.googleapis.com/css2?family=Brygada+1918:wght@400;700&display=swap&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'">
  <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Brygada+1918:wght@400;700&display=swap&display=swap"></noscript>
  <link rel="stylesheet" href="https://r.mobirisesite.com/430795/assets/css/mbr-additional.css?rnd=1715149129646" type="text/css">
<!--  <script src="{% static 'assets/ytplayer/index.js' %}"></script>-->
<!--  <link rel="stylesheet" href="{% static 'path/to/your/css/styles.css' %}">-->
 <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">


   <style>

       .favorite-icon {
            font-size: 24px;
            cursor: pointer;
        }



.button-container {
    display: flex;
    justify-content: center;
    gap: 10px; /* Optional: Adds space between the buttons */
}
 .card-container {
            margin-bottom: 1cm;
        }


    </style>
  <script>
   let favoriteCount = {{ request.user.favoritemovie_set.count }};  // Initialize with the current count of favorite movies

function toggleFavorite(movieId) {
    const icon = document.getElementById(`heart-icon-${movieId}`);

    if (icon.style.color === 'red') {
        icon.style.color = 'white';
        favoriteCount--;  // Decrement the favorite count when a movie is unfavorited
        showMessage('The movie has been removed from your favorite list.');
    } else {
        if (favoriteCount < 15000) {  // Check if the favorite count is less than 15000
            icon.style.color = 'red';
            favoriteCount++;  // Increment the favorite count when a movie is favorited
            showMessage('The movie has been added to your favorite list.');
        } else {
            alert('You can only add up to 15000 favorite movies.');
            return;  // Exit the function to prevent further actions
        }
    }

    fetch(`/home/favorite/?movieId=${movieId}`)
        .then(response => {
            if (!response.ok) {
                throw new Error('Network response was not ok.');
            }
            return response.json();
        })
        .then(data => {
            // Optionally, handle response data if needed
        })
        .catch(error => {
            console.error('Error:', error);
        });
}

function showMessage(message) {
    alert(message);  // You can replace this with a more sophisticated message display mechanism if desired
}

.search-btn-oval {
    border-radius: 50px; /* Makes the button oval */
    padding: 10px 20px; /* Adjust padding for better appearance */
    background-color: #007bff; /* Button background color */
    border: none; /* Remove border */
    color: white; /* Icon color */
    display: flex; /* Flexbox to center the icon */
    align-items: center; /* Center icon vertically */
    justify-content: center; /* Center icon horizontally */
}

.search-btn-oval i {
    margin: 0; /* Remove default margin */
}

/* Optional: Adjust hover and focus styles for better UX */
.search-btn-oval:hover,
.search-btn-oval:focus {
    background-color: #0056b3; /* Darker background on hover/focus */
    outline: none; /* Remove focus outline */
}

  </script>
</head>
<body>

  <section data-bs-version="5.1" class="menu menu2 cid-uca1Sf64NU" once="menu" id="menu-5-uca1Sf64NU">



	<nav class="navbar navbar-dropdown navbar-fixed-top navbar-expand-lg">
		<div class="container">
			<div class="navbar-brand">
				<span class="navbar-logo">

						<img src="{% static 'img/movielogo.png' %}" alt="Mobirise Website Builder" style="height: 4.3rem;">

				</span>
				<span class="navbar-caption-wrap"><a class="navbar-caption text-black display-4" href="">CineMagic</a></span>
			</div>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbarSupportedContent" data-bs-target="#navbarSupportedContent" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
				<div class="hamburger">
					<span></span>
					<span></span>
					<span></span>
					<span></span>
				</div>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav nav-dropdown" data-app-modern-menu="true"><li class="nav-item">
						<a class="nav-link link text-black display-4" href="{% url 'home' %}">Home</a>
					</li>
					<li class="nav-item">
						<a class="nav-link link text-black display-4" href="{% url 'note' %}" aria-expanded="false">About</a>
					</li>
					<li class="nav-item">
			 <a class="nav-link link text-black display-4" href="{% url 'favorite' %}?movieId=3">Favorite</a>


					</li></ul>


<!-- search_results.html -->
<div class="navbar-buttons mbr-section-btn">
    <!-- Search bar -->
    <form class="form-inline my-2 my-lg-0 mr-2" method="GET" action="{% url 'search' %}">
        <input class="form-control form-control-sm mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-primary btn-sm search-btn-oval" type="submit"><i class="fa-brands fa-sistrix fa-2xl" style="color: #ffffff;"></i></button>
    </form>
</div>

			</div>
		</div>
	</nav>


  </section>
  <section data-bs-version="5.1" class="header18 cid-uca1Sf79tk mbr-fullscreen" style="background-image: url('{% static 'img/movieban.png' %}');" data-bg-video="https://www.youtube.com/embed/I_KfwTmcAN4?autoplay=1&amp;loop=1&amp;playlist=I_KfwTmcAN4&amp;t=20&amp;mute=1&amp;playsinline=1&amp;controls=0&amp;showinfo=0&amp;autohide=1&amp;allowfullscreen=true&amp;mode=transparent" id="hero-16-uca1Sf79tk">
    <div class="mbr-overlay"></div>
    <div class="container-fluid">
      <div class="row">
        <div class="content-wrap col-12 col-md-12">
          <h1 class="mbr-section-title mbr-fonts-style mb-4 display-1">
            <strong style="color: white;">Movie Mania</strong>
          </h1>
          <p class="mbr-fonts-style mbr-text mb-4 display-7" style="text-align: center;">
            <h4 style="color: aqua;">Step into a world of cinematic wonders where every frame tells a story and every character steals your heart</h4>
          </p>
          <div class="mbr-section-btn">
            <a class="btn btn-white-outline display-7" href="">Explore Now</a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <br>
  <br>




<!-- favorite.html -->

    <h1 style="text-align:center"><b>Your Favorite Movie Collections</b></h1>
  <br>
  <br>
<br><br>
<div class="container">
     <div class="row mbr-masonry" data-masonry='{"percentPosition": true}'>
        {% for favorite in request.user.favoritemovie_set.all %}
            <div class="col-12 col-md-6 col-lg-4  card-container">
                <div class="card bg-dark text-white" style="width: 23rem; height: 40rem; position: relative;">
                    <img src="{{ favorite.movie.image.url }}" class="card-img-top" alt="{{ favorite.movie.title }}" style="max-height: 240px; object-fit: cover;">
                    <div class="card-body">
                        <h5 class="card-title">{{ favorite.movie.title }}</h5>
                        <p class="card-text">{{ favorite.movie.description }}</p>
                        <p class="card-text"><b>Release Date:</b> {{ favorite.movie.release_date }}</p>
                        <p class="card-text"><b>Actors:</b> {{ favorite.movie.actors }}</p>
                        <p class="card-text"><b>Category:</b> {{ favorite.movie.category }}</p>
                        <div class="button-container">
                             <a href="{{ favorite.movie.trailer_link }}" class="btn btn-primary">Trailer</a>
                             <a href="{% url 'review_page' id=favorite.movie.id %}" class="btn btn-primary">Review</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>




<section data-bs-version="5.1" class="social05 cid-uca1Sfat00" id="follow-us-2-uca1Sfat00">




   <div class="container">
        <div class="row">
            <h3 class="mbr-section-title align-center mb-5 mbr-fonts-style display-2">
                <strong>Join the Movie Mania</strong>
            </h3>
            <div class="col-12">
                <div class="social-row">
                    <div class="soc-item">
                        <a href="" target="_blank">
                            <span class="mbr-iconfont socicon socicon-facebook"></span>
                        </a>
                    </div>
                    <div class="soc-item">
                        <a href="https://x.com/AntonyPTjomon?t=HRuVJo8vvCXa6FCISYlbBg&s=09" target="_blank">
                            <span class="mbr-iconfont socicon-twitter socicon"></span>
                        </a>
                    </div>
                    <div class="soc-item">
                        <a href="https://x.com/AntonyPTjomon?t=HRuVJo8vvCXa6FCISYlbBg&s=09" target="_blank">
                            <span class="mbr-iconfont socicon-instagram socicon"></span>
                        </a>
                    </div>
                    <div class="soc-item">
                        <a href="https://www.instagram.com/j__0m0n?igsh=eDNvaWdodnNyZWd2" target="_blank">
                            <span class="mbr-iconfont socicon socicon-linkedin"></span>
                        </a>
                    </div>
                    <div class="soc-item">
                        <a href="https://www.instagram.com/j__0m0n?igsh=eDNvaWdodnNyZWd2" target="_blank">
                            <span class="mbr-iconfont socicon socicon-twitch"></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section data-bs-version="5.1" class="footer3 cid-uca1SfbALD" once="footers" id="footer-6-uca1SfbALD">





    <div class="container">
        <div class="row">
            <div class="row-links">
                 <ul class="header-menu">

                <li class="header-menu-item mbr-fonts-style display-5">
                    <a href="/home" class="text-white">Home</a>
                  </li><li class="header-menu-item mbr-fonts-style display-5">
                    <a href="/home" class="text-white">Movies</a>
                  </li><li class="header-menu-item mbr-fonts-style display-5">
                    <a href="/note" class="text-white">About</a>
                </li>
                  </ul>
              </div>


            <div class="col-12 mt-4">
                <p class="mbr-fonts-style copyright display-7">© 2024 Movie Mania. All Rights Reserved.</p>
            </div>
        </div>
    </div>

</section>

   <!-- Include the JavaScript file -->
  <script src="{% static 'path/to/favorites.js' %}"></script>
  <script src="assets/web/assets/jquery/jquery.min.js"></script>
  <script src="{% static 'assets/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="assets/smoothscroll/smooth-scroll.js"></script>
  <script src="assets/ytplayer/index.js"></script>
  <script src="assets/dropdown/js/navbar-dropdown.js"></script>
  <script src="assets/vimeoplayer/player.js"></script>
  <script src="assets/masonry/masonry.pkgd.min.js"></script>
  <script src="assets/imagesloaded/imagesloaded.pkgd.min.js"></script>
  <script src="assets/mbr-switch-arrow/mbr-switch-arrow.js"></script>
  <script src="assets/theme/js/script.js"></script>
  <script src="assets/formoid/formoid.min.js"></script>
 <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Design by foolishdeveloper.com -->
    <title>Glassmorphism login Form Tutorial in html css</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <!--Stylesheet-->
    <style media="screen">
      *,
*:before,
*:after{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    background-color: #080710;
}
.background{
    width: 430px;
    height: 520px;
    position: absolute;
    transform: translate(-50%,-50%);
    left: 50%;
    top: 50%;
}
.background .shape{
    height: 200px;
    width: 200px;
    position: absolute;
    border-radius: 50%;
}
.shape:first-child{
    background: linear-gradient(
        #1845ad,
        #23a2f6
    );
    left: -80px;
    top: -80px;
}
.shape:last-child{
    background: linear-gradient(
        to right,
        #ff512f,
        #f09819
    );
    right: -30px;
    bottom: -80px;
}
form{
    height: 520px;
    width: 400px;
    background-color: rgba(255,255,255,0.13);
    position: absolute;
    transform: translate(-50%,-50%);
    top: 50%;
    left: 50%;
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
}
form *{
    font-family: 'Poppins',sans-serif;
    color: #ffffff;
    letter-spacing: 0.5px;
    outline: none;
    border: none;
}
form h3{
    font-size: 32px;
    font-weight: 500;
    line-height: 42px;
    text-align: center;
}

label{
    display: block;
    margin-top: 30px;
    font-size: 16px;
    font-weight: 500;
}
input{
    display: block;
    height: 50px;
    width: 100%;
    background-color: rgba(255,255,255,0.07);
    border-radius: 3px;
    padding: 0 10px;
    margin-top: 8px;
    font-size: 14px;
    font-weight: 300;
}
::placeholder{
    color: #e5e5e5;
}
button{
    margin-top: 30px;
    width: 100%;
    background-color: #ffffff;
    color: #080710;
    padding: 15px 0;
    font-size: 18px;
    font-weight: 600;
    border-radius: 5px;
    cursor: pointer;
}
.social{
  margin-top: 30px;
  display: flex;
}
.social div{
  background: red;
  width: 150px;
  border-radius: 3px;
  padding: 5px 10px 10px 5px;
  background-color: rgba(255,255,255,0.27);
  color: #eaf0fb;
  text-align: center;
}
.social div:hover{
  background-color: rgba(255,255,255,0.47);
}
.social .fb{
  margin-left: 25px;
}
.social i{
  margin-right: 4px;
}

    </style>
</head>
<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form method="post" action="{% url 'login' %}">
        {% csrf_token %}
        <h3>Login Here</h3>

        <label for="username">Username</label>
        <input type="text" placeholder="Enter your username" id="username" name="username">

        <label for="password">Password</label>
        <input type="password" placeholder="Password" id="password" name="password">

        <button type="submit">Log In</button>


<!--    <button href="reg.html">Register Now</button>-->

        <a href="{% url 'register' %}">
    Register Now
</a>




<!--        <div class="social">
            <div class="go"><i class="fab fa-google"></i> Google</div>
            <div class="fb"><i class="fab fa-facebook"></i> Facebook</div>
        </div> -->
    </form>
</body>
</html>